
@startuml
title 基于GitHub的实验管理平台--类图

class users{
    +user_id:int
    +name:String
    +gitbub_username:String
    +update_date:date
    +password:String
    +disable:String
    +getUserInfo()
    +setUserInfo()
    +setPassword()
    +getPassword()
    
}

class teachers{
    +teacher_id:String
    +department:String
}

class students{
    +student_id:String
    +class:String
    +result_sum:int
    +web_sum:String
    +collage_name:String
    +course_name:String
    +getStudents()
    +setStudents() 
}

users <|- students
users <|-- teachers

class grades{
    +student_id:String
    +test_id:int
    +standard:String
    +result:String
    +memo:String
    +update_date:date
    +setGrades()
    +getGrades()
}

class tests{
    +test_id:int
    +title:String
    +summery:String
    +update_date:date
    +teacher_name:String
    +course_name:String
    +collage_name:String
    +getTests()
    +setTests()
}

students "1" -- "n"  grades
tests "1" -- "n"  grades

class courses{
    +course_id:String
    +course_name:String
    +summery:String
    +number:int
    +teacher_name:String
    +collage_name:String
    +getCourses()
    +setCourses()
}

class collage{
    +collage_id:String
    +collage_name:String
    +student_id:String
    +student_name:String
    +number:int
    +getCollage()
    +setCollage()
}
students "1" -- "n"  courses
collage "1" -- "n" students
@enduml